server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp-client
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max-2025-01-25

    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            my-lark-server:
              # 实际的连接地址为：http://localhost:8080/sse/mcp
              url: http://localhost:8081
              sse-endpoint: /lark
            my-rule-server:
              url: http://localhost:8080
              sse-endpoint: /rule
  mandatory-file-encoding: UTF-8

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
    org.springframework.ai: DEBUG
    reactor: DEBUG