server:
  port: 8081
spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: my-lark-server
        version: 0.0.1
        type: ASYNC  # Recommended for reactive applications
        # 配置 sse 的根路径，默认值为 /sse
        # 下面的最终路径为 ip:port/lark/mcp
        sse-endpoint: /lark
        sse-message-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

# logging.pattern.console=
