// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RpcHello.proto
// Protobuf Java Version: 4.33.2

package com.yohan.javabasic.java.protobuf.hello;

@com.google.protobuf.Generated
public final class HelloProto extends com.google.protobuf.GeneratedFile {
  private HelloProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "HelloProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yohan_javabasic_java_protobuf_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yohan_javabasic_java_protobuf_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yohan_javabasic_java_protobuf_hello_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yohan_javabasic_java_protobuf_hello_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016RpcHello.proto\022\'com.yohan.javabasic.ja" +
      "va.protobuf.hello\"\034\n\014HelloRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2\203" +
      "\001\n\014HelloService\022s\n\003Say\0225.com.yohan.javab" +
      "asic.java.protobuf.hello.HelloRequest\0323." +
      "com.yohan.javabasic.java.protobuf.hello." +
      "HelloReply\"\000B\033\n\005helloB\nHelloProtoP\001\242\002\003HL" +
      "Wb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_yohan_javabasic_java_protobuf_hello_HelloRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_yohan_javabasic_java_protobuf_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_yohan_javabasic_java_protobuf_hello_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_yohan_javabasic_java_protobuf_hello_HelloReply_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_yohan_javabasic_java_protobuf_hello_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_yohan_javabasic_java_protobuf_hello_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
