server:
  port: 8012
# apollo 配置
apollo:
  bootstrap:
    # true:will inject 'application' namespace in bootstrap phase
    enabled: true
    namespaces: application
  configService: http://192.168.3.87:8080
app:
  id: apollo-quickstart
env: dev
yohan:
  key: config in local application yml

# 监听配置更改的namespace
listeners: "application"

