server:
  port: 10001

spring:
  application:
    name: spring-ai-alibaba-deepseek-chat-model

  ai:
    deepseek:
      api-key: ${AI_DEEPSEEK_API_KEY}
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      chat:
        options:
          model: deepseek-v3
      embedding:
        enabled: false